/**
 * Created by huyhuynh on 8/7/17.
 */
export const FETCH_SESSION_LIST = 'FETCH_SESSION_LIST';
export const FETCH_SESSION_LIST_SUCCESS = 'FETCH_SESSION_LIST_SUCCESS';
export const FETCH_SESSION_LIST_FAILED = 'FETCH_SESSION_LIST_FAILED';
export const SELECT_SESSION = 'SELECT_SESSION';
export const FETCH_SESSION_DAY_LIST = 'FETCH_SESSION_DAY_LIST';
export const FETCH_SESSION_DAY_LIST_SUCCESS = 'FETCH_SESSION_DAY_LIST_SUCCESS';
export const FETCH_SESSION_DAY_LIST_FAILED = 'FETCH_SESSION_DAY_LIST_FAILED';